services:

  client:
    build:
     context: .
     dockerfile: './@app/client/Dockerfile'
    ports:
      - "5173:5173"
    volumes:
      - ./@app/client:/var/www/@app/client:cached
      - /var/www/@app/client/node_modules
    environment:
      - NODE_ENV=development